[package]
name = "ilex-attr"
version = "0.5.0"
description = "attributes for the ilex crate"

edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
keywords.workspace = true
license.workspace = true

[lib]
path = "lib.rs"
proc-macro = true
